[cors]
allowed_origins="http://localhost:5173"

[tls]

[tls.server]
# cert_file="certs/server.crt"
# key_file="certs/server.key"

[log]
level="DEBUG"

[ogimage]
base_url="http://localhost:3000"
# browser_path=""  # omit to auto-detect Chrome
